replicaCount: 1

appPort: 5000

image:
  registry: 797606048546.dkr.ecr.us-east-1.amazonaws.com/flask-app-ecr
  tag: latest

# environmentVariables:
# - name: FLASK_DEBUG
# - value: development

environmentVariablesFrom:
- secretRef:
    name: mongodb-credentials

livenessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 20
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /health
    port: 5000
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 5

ingress:
  enabled: true

host: flask-app.797606048546.realhandsonlabs.net

mongo:
  database: AgADlAsFYdHjemdxwGA9PRR9qFfLKtLel2QFc1xsjeY0/i2/ZVZy1bEyDxHDUTLo0SEfsbCdJtXuXXTZnM8i/gCD572GKNaOf3t6r6OiQjrEe4RRG0pVlx9tYXtwwXfUTWm6ebF27zlR7/sT8MPkZF/TxFIw9//34Ugv+jdXe0ExiLmW5IBCibIJS7AF3bTi49DKlIsx4QIEnZTpHx5+JmbwZLN/4cy2iUGbuR2V9K6rVhGCVby3gIniMuR4fjDDj0/DXWJ2g6Q/TZmo5RGdvWvbQ3zXknhyC0guTmA9P5BPtHBobWzVXNTaM0alrhvVQCAkUXNIqpx11AXPAYO7VrNuLC78z/wUN0H4qJo8kd3KTzqnnQ8cbYbdW5OLm1szrrc8PANbbfLvfh3X4WubWmX03T/mIQPBeXTLxH8AmFxSnCJ9t39MpCVdvoeI2lFJDtpvaVO8CWex+SOTQQfDA/hzD/13yaHL3SjtkQ/t8iOcBzXhiTuQmoirOY6ZLQBFDtiQ6xciuPus0XOchLHvGpsTXM5uMxajc667QntmOwlV+h/4sJnVj0zdi/dAL+abjnleNRA0DuJwEzkPr+/77vNrwS/JuRzmivMxIG3p/9R1ixNRsF2B/LaZ5WBgAIwXUt3SxEDVtXan8HrsKB7u/Fg3Q8YshuA9d1OSUtLbKmRLOgaME+hDrhRArONIjVK1wcSm2ClFMQ==
  host: AgAxcsdrrMZ9qCGuS28nBivF56bfMOnHRo35WTFgU1A38Q5ZWW2ycWv3KPMyk9G0qzdhG9WUjoDqsQNHRgkW/ydWRq7gxub8Ue/JJOeoxt2zihj/Nqr3WH0XArDPz+2mGAy7Io3oTc/m/4rry7+lL0LPw+TMvicqh5ekQCWnOJX3gczmPfIydQ8RMy4crKCKCSN7D9cpfgnEFUbexUxtxV0hsa/gsMNEYLYMybpoTf1oJGUT+kAfARsMKq1RM9euONr6Dev3korJFeAR5hrK2YWRBO9NVXNYOz8YDkxLMFQjisK1bzxeLu9Gt1r4m4Kn/RRUqn0j4HvKFwtw4kdiLgrWs4bGaTF9lzOQXIoBL+pTjgZr1b5hBnXAtJrhGc7c4j+rOdNbpaukXpCyzeg8Uf5FGVXpsBm/0Q+xBckKoQo2AGL7Gh4Qu1wySs6rgKLTn1P8tW9Lo6uA7WnqZHBT1lvIanYH0cv41c0ox0iVcO6AGq1qDwdyfVwe9OnzIQELhi7nOrxmUPf/uTk7EvXvTDWuBGzoNDqqs+m14PCPAjzr1JKPD/T/Fuk+HS6bL/JVon1Bo+JUjz4o6126l+PU7fU13QwKhMblhtk7T7v3DQq9YCu4pcW/DP73nVRqhCNUbSX9aL/bqQdr2T4mOC+92a8tTzG7xp9DtOehYOviLBOIsy/L66TOYSBbKfhcmaqU01S5ITY68fkZ6QKRh4rjEJGN/B5whVjT1hL6RjTFA4ldfTszcI/xAQdUrjIO1A+EWQUnGZ+TlXyGQyVCuio=
  password: AgC8/VjEpLugWgtaR0gl6wODpOOE1VT6uxOyef4I0QV3dgXhoUOiIrVXGIFYRm0Kj1bXf7eRJLY/tLNZ4SO/odraz+RTQR8G3Vh/m4zRhiiBaUmRLXbX2c71bj0ej7poEeNau8lS1v+vqLMJOrlrk1O+sw2J3MAHn5AMaJc8e3oNcK/3l5KhrpdprlXtntiNuLWi1JXqt2k3x6zGZracrZXMjszfonT0dPTWaLwwcI9RwziKME4itm2z083a1I9iMFB4vqqrdM+5380uE54kFCz+eBczcoSTS6xCuxUpEJcEHZfLzecSXDOmWvgn087NTTwkkVaLC1h0qk2Qt3ZkUBx3jhzAYZyt/7xsl4PbGNW/Tz+BW1B5oxjydDjOoyXMh50r85G25oXkcYUbkCmuvq57SGE+gvsDOqqoZeVtVBz03NL5Qatm3k8SRKYCy0U0C929Ze7NrjEIFC/7DBjMUH/Vksp+Iw0wSmUfBzB8bEjhKVz0Tiod/i2HucaKoGO1BmsiEjXmrsjHgRAXA1g4Ny1HTTurHvQ27bmYk1EJSXGM9weXI4BgExBZ1L06vCOM0J783mcSt5q51OcGdDL1Tcr63v4l3d4D4UeA8C2pngbpnX0dYhOQePeowagAjY9CoRyoh9sB2lw8xQCWyE3u3oUOWG1kyYM+rso6nCczBsrlGaNcXh0/EigkWflCOYBGC1GdPPKgTs2CSDCBrTE=
  user: AgCIaaldAOlXe4gPP2Nb4H7IBiissbQ2HaNplWSKDcmqUh1vbiR2c9MZQhaJobjXwBaMM+TiJw3bgm2AfsWMs/y+ntHVU/zNCW6DEneKsOuEb7dg3i6qhcwyHg2DpsTUyVfzJOOGYMRFQWhwxwGx5JCz2m51l4zAOSjakxbSZSqtwoNbTDZyR06TtK+A5ZXYc+phw1lPxCKPpAMaAv7iyNIps1A8xgD2ewpgx5PVqOi13l0BsC1KdKAHMQxo+cb5NnviARDzgLA3kR2JyRn3hzNa/LS+vfWmodLIUAwJ4khY3AF2HGZQf1QnY7wiwjG7NEGbXhSXOvW1Cz/2NgUKVrn752+eX2E4HLx9hWuv7K5bmymYQgymyJHql6QLDZEopKy+8L8OOc4qvlAjVohyvJAFoLT91xoQ2DhY8O2z7kNswLt3LCu/79qPBZirNikZjncOlS1bFEpBqt8EfvuDGpJ3KEC68Hd1qeIBRaE06DsLRQ4GnTPC50ttb5AmzEpZe60KoVhTy3w9/jh7O5XqSDwbxjGLwXrpfsg+//EAk4VxeGz52PDu3hCdL/jR0AMrNe9eu+GN/foSPtHQMLERKj8dj5rwOJoxI0ZkEoMon0y62ZPB182EIIpLavYFfbTuuMKWetk2LXwtlQlJxPg/5rUHhP4VstFgxz7G/Pvy9adB+/li7ZJv+qEHScCukb55IOUE1MuT02It

