replicaCount: 1

appPort: 5000

image:
  registry: 797606048546.dkr.ecr.us-east-1.amazonaws.com/eks-ecr
  tag: latest

# environmentVariables:
# - name: FLASK_DEBUG
# - value: development

environmentVariablesFrom:
- secretRef:
    name: mongodb-credentials

livenessProbe: {}

readinessProbe: {}

ingress:
  enabled: true

mongo:
  database: AgBq3QNlxur6QPCInI8dphLKk5PS1zsVicF7izGNJ1dvP1hrZewKqA0jABOavjTEB0bmuoBna2NPqDu9gkOxox6gzUK7YaHlWDWMsNL6D65junNK4AUPUd5sreqaAJh2zg53eQy2bVDWPk9w7+BqGKqFmvrJDp+IBAQG7rVYqSbsOY4XJoXIlybNbRJ6NsYzOidLJhUqmQ1mRYo6P3Tg3AcTYoDuBDehPwRYVdwSh+5stPuzAwlRAzwuaEFTbf9BSAl5Lph1LbJQu9Wn/qbvYhLItQjIttyZv+t0hiLQUZUuePlabz+h9I99Y+RZE4qbWFhUPcMohiGmUgZofQrhqrRPcrAC8DJyZsOkgZnWy10tIpxShJVaixK0V1vlngcTtg3+GxuB4eq/ENQpOJcmXXYLNgqxJWDRdI5gXHxPjoWMa6LVeg9/2dt4l5zDxHz4X7mNwt+TRqeQOmYAUNmHx+yn+/MIegDuHoBXlERs8AVjklma4fCMtl8hB5uMwc2FaqkKgk8tgJjZJgQjiD19MGh++QSq4kxpG1Rlq9kil4YIlxHjtlk8mP/nWzcIm+6zfzyXR3wUPX5lah0aK9NXuOMYbUqbeNp0UvJ8qGQeMlB2eCdBjf1yrskjQn7rxKIGy/jVx4tVzSbTnVOyFrVeME5esv6eHL3Xha8qYxKSuMbiW2WIO7FNN+dPQh9rP9GYCQB2EqcbDg==
  host: AgANB72SMS4Ugu/0rLBNODveHd1f/5A3zzkLR3WQmINSozjsE52/D/adceaXzvgCEyQjPZjoAoPTZzL7W+GlgYgXq3edQh6g+/qfXNO6IMiWqflhFRFCZKkiffRjemY1gsyGseHu6PCic4IaNv2Rdl8TyecEtACLrrjpQ12WzxccBJbsoDDM/TZeniPoQLwP0W7pab36T/YCavv6q417q+PXSJ2KxZ0s+JWxyUYIJJXEedq4G4ZfkLeJ+K3mvv7Xc0x59tBMS5Nhmng8aNA9R+i9I8gGNx20yJKXaEsVmiPhbJzuE3AsMWvYfxN40a9XheZIi/GCe1BXhJcOR5GRPb7OM97VL0KwbiNimaIr5DmBlwRufkNAM4F1t3PbVbGeJEo1MIsvCkHvnUsJnsUjCX9dmYPBbf4s8iQXi1WrcREJ+C5nmeONOG6Ll7DpjLDQSSj/JITet+cWKs/ZL5l9EPIGSUtKceXYtYVy9sWpwYahAr1ACJ3v8xIayL2T4u29+ITSzRzKvN4mvcqIAD+CZWu/yITkhACaORXGT8/arDob24abafM9gb2F2K06Z9+38an3L/JWOW1qaACIQct25Jm6QyfUHzCoyTicdykPnIdf7PKVcZ5/U/0SdHvqn/69CGrSmwTt8kmwcsD0QHaGOyIahhCWwrBnPBHBoqd9DGuD6dOf6dP1s2gaWsapc336PG1y5cR1JAGCDbJs71Gnf3pT2xv6JYk1WiFbVaMUsXG+02X5AOL3f4mRV3GFPcDrrSxCYz8vH9SG0HdZQzwp
  password: AgAUyvlc/JQssm8ID5D2GkUoqDsRAZWgPnK5+SMWBURrUAeYU6ZR+ka17txpAlNZuW0za/5gVDIvXA09bdiEa2xi7xKdneQpUDn+mtmbVwwiVXsf4BA+xiDOqm4FF0hnx5Mjzsb+TCuvBujvTWt1mftnCuaspCDkQJle5F4+7R5a6U1epafK8DoEGoQVHmAS3c+IcjUu/zYacys03kt5+6zFTdY99KcoBztRWoB21perS2OEkFwuQM/U4n/qdUqIfaAkjSjP2zRvMqej6Wa8NS833uLoy0HkG6OgRJV6JtJHv9DvI9op/OxzzDw8AF11V+hpKFeaLWMTZGbjzyHbG006CDwI93Y156Si8YW005z7LtszB0ogi6J58RTDhezghCb3UiBpLfalKvfrkTHECRIdEyy3wHtZw5Wsc/mm/bjsYSeQrubjDk7s2M/HpQrnfs09P77Ctzy5UUUyg8l0pP8MaIuICv8HqTPLPDthDdGxoYqh3ChHF7zlYoO5QKnW99pMwsKjuGB1KothucQheCTJnmbYIaiusZUHyoagxTq/WnBRxEQ15xIbCtT78QKdYsQSvoQx6LGgN3bsgJnE1tXd/5MyaDSUjAgjYjT2osff7RpnJx5lhD1civ413Yi7KLazo9YepCc6/MzvffwyedX/MYJSt/s4cYp7s/O3y1sW0xMMgGUU0uU7UOUxNaVDPhBErjHU5cfPBKlikgQ=
  user: AgBNnkL5pcjBkBMMNHwT2kmxt2TKpQIUaNNaK6EtVfxPN3vUu3ccijxZj0bJYrOI3fuuzNB3TQX6gUyTLaHFDbe0GNE85uzsZS66mCFTcrvNxGq/pvZMsZsTI/g4einXzNsup27XH/VgmMzTiGFQmLBEwrE05rzTsdx1IAR29mq7vSiwwPV5n1srQLshoCmXDj+pStWnU8JqOglg8fBnreujytHumrnqttdEDVLjNmquSBBOeMT+ZnpTikKw4Kms4Q9qvpdHRxniYyukrTvzU6MKYWTGMVkvqF55EC+8133FWON3W2B+goJ7Yu3eVzf4jR6n9Eekk9aikHSijZPPzuyacoAjyE70JWWABYlGU5HkwBxfJUdJmU/jyws5BXHXZYoNcTZXf//1az+k7pcBWy4wazqnB4UqPhLI6cJnbvLkgunA0NTy0X2wfXCoX0OQqhPP+oU0spHoR3pqx8mRCI6iE+qo04i2EFeoaPku+8P3r8FrVGGAmenWDFizkMRQIucf8A79vxpRoUW6fO6JEemrBcm7bJGSmP9XAeJzpSSIo4Gq0bEU/0wOdXayyFl9OlMFu/OMSsNlvpjIUM/dxo9GyVYTKdnGpmj+4nUUu0XMffw8Jr5uBYabrZo1NLLodX0BNthfayJi8q6KxYd+xVfjBfQlNVWr1wLC/vW0kSfdmKfOgLDYTnsQpFZpXa4Ul125Kkp75OXf

