replicaCount: 1

appPort: 5000

image:
  registry: 381491904201.dkr.ecr.us-east-1.amazonaws.com/eks-ecr
  tag: latest

# environmentVariables:
# - name: FLASK_DEBUG
# - value: development

environmentVariablesFrom:
- secretRef:
    name: mongodb-credentials

livenessProbe: {}

readinessProbe: {}

ingress:
  enabled: true

mongo:
  database: AgB8gDlJfHiQeJcLNOeatnz3d0Y5c0q0OItfi1N0r9wJU+vv25GEsWBrjnr94xQMTb7Sw+ceS7GytQjyJ7xhR0J/8PdLn08bsRb1RoDUs4Bue3EFTUDRYfKCd1vwwUgXiNNiofMf6lahghSsr9BYfhEcQvt0zp2WQrJ00bZsoDMYYKE6waIgXXaR5dluTyWz+1VMkfN61CzFkAiEI8wHIRpzhDLviKwBItc9csJnAAaiGr2sf0Ti48E5AtC5UEKiYb8MMSEq7GW+nt+V+RJePcuPCzY+jtAacMUyHi+mRFjcNa2rUvcXDis6eGIHnJqN1bP5dTh5BvY1NP57RNdOZ69iUptoVUuj49eVAVU3X7r1FWFkbiIakEtdSjErFukWwxHi4IJoOqNy2GlW3n4matyC4FAUra6tMtqd/yTYVdmyXq2d1AhxHYEs7dx7UiioAz3KCzckMUdvUdqavwfVeG0dM+oSgpWYUg5Lp02lPdrCNdtGGv4PUSiXEjt0WEyr2wGgUGGJcyLpELJWU+4lrwHaq/mQm+jC1ZQ5P4GtIr1aG/Yp2Bnr3TSNiFmbyX3laeLJKnJN98JjEdyMVJEBXyJXTOhc+jA5kSPRTXhdZSc6E68+rpXhC4U7rahmslscqPoq1QRg0KXe4u8gSKZlhxXFrLhQ3Acw2C+Z77jZFU0lKzyJ8fHKgP3RnZgFw7R0/sYZPZ1xyw==
  host: AgCtDo/w2o55YgxztIUrLkUrr4quXID3cVfbGfl46E+MnJNvwAf+bklKuRpEgMNA7+EougcuxZ+xlAWdqsIBmvEjIg96M3s0X8D9DTzTdeQJYQQLEXvDePXIRrCqCY8ywN9diieno/UzJ/DzHqXNjp7LdHgVYNYJhm1USJ83VgaEIFEf7RmAHGY5/a/VP4KXTKlIQ+D5XADNYIBqaU9eBcbKZ42xVSDP6r4jlrTFDHwEMt1WC4kSlOdNNZgKRJ12flv0xHC3LJv3sLUJ45PADEu7WLt3pF/KxJnF1btucKNFf7OOOY1zpI1DY2UdgkbDsm7BsTSRhw8NestffyMEcH2s8dJsXXTZHncWHM9ZzcRaQEScHZ/MDZsGrlIQhRkb7ULDJEONxyxS1RXHlWss2zKDY6gcfjqVXZgTTweQEnk1IfpCXZH2FXwweOqm2S4GoDwbqefv3MVaNQn0Aqosr5G2ku7mvwylNlVyyVt/N/QJbnzHxqAu/KvioDSRsdVX3Q355NTeqqY5nyhXnvV2ybwofia60fVgbq9mvfNMC/B0jq1P5Poxlwxazd/ns01Jc0X8GEPMf3UQm0hfCgAqajokigclHFdxBgCKkqrmP+dctgHLn9To2TkLC2iUBzgdmvtzQHpwK1zQfztGQ9W36H0PaWO8k24oH8rorteNVLb+Ii5s4uDzRwF8zlKuwzitiPWMFES4gOveg3D5Mg==
  password: AgCpU+qvDNm65YfNbeoBa3k9F6opgJ7yWQFQHvZxz8Bg38VcrbgZPzteFWc69Aj9vfVmF8iferLoE+afMP8lR/pG+4M5GpVhDak84RQGlGSf39eWZCdqsGiAO7L5v0Fg9kmn35wzJnw5fcTzhKfNJK96rLOSm/uFpOsENRykjJIVo3ggFC3zM5ulYFVAKGbQe5w6QdpFyo2i6xYVgcB52LO7hfSW3WC+6KGa4T3Oq+UdldE0iRBmw8LFBdxOEYXYcsZcjiT5Ivc5mGSJ6DOWVM7UzzqxsYwuATB92zGKoidU1x2WH+GVVFIDF9qIIoO+Pl3aS6bwcSGxeDkUpyh8VhOywiPElAEtmSYqmJiayndCguJcSFju9fEVbPrfoTt6uuOwjNA9u6uWCPE3LYGtYSk7jR5X6qRusW9wcV4bplH8J0LB+Hlz4xnDbCfH4dAWZRiUhQiEh8nmk5a318FQ54XeWk1TP4O0TVIMsnpW1kLMgP3r5mNfUSl8LG1vGFQdtbl7adioOLLuyPhrzkQgrtDPRE9Xkrrkpw5wDGhpTSrQB1/+BYo5wBQ1FgvrdQkVLwGb4kwJW/89NLLA9VM9jeSaQGiqtE7Ay1HQxLz/DFgMmBXEJdvP2hs8DvgI5oidA/0TOf3YdmiqKgXXga/lwSbyMpm8F3hV/uPgFYY8C8ZzjeuHhOx28Tuzr+Zf9B7W2mkEWGuhy+TJFS5rsbg=
  user: AgA5/fxbC8gaTo3QqSDFBeG/qidF9BhAJ7O4x/S4K8BgpUxOBATv89dE14iPc2pdapfkatZSsUUNqsu3jygcslUqvLE0qAWH987jcpGlEMSZDKTU+NMKJftlNDq77uSWKEcEM9O+yqJcSzduo5uzVRUIg3PlG13RXTOcmnnV4+eB6HzSl8CqwP8chxQw6pFPRB9mfsN76J8ZReFyoPNI3DeG8vg2+0e8je75AucT0kw213iyEaoouRCpN78eqndvB8+FmOfxayrmFddFNLTlN4iaZIdUqFr0FDEmYYtWryIJKK3p85XC/Crj5cNn+LIJFpmH8fV/mceV6kEyr0XoXTl6KD2hsIApurkslCRX9BmEUsyUKfG5JTrrnA0ynN2+rU51OCpsmcQJkvhQ80qLBNZwa9rUZczSsPs7Gurfyp135StQ5C4WyJ8ZysRKDsyC+Gpvd6ituti76Fb4Sk0hfeLW2A3BLg6yepBykXAMM7xK+zCv+HiHrXqmSc0iEPmPxcYTFNnPxIuFLbQZ53Ftl9CmHYdcPYo/Lq7blBT/AoEG5c28Bus+e6P2yHrdNrcqu8kDFocp9MI5CyBwutzgcLfokW2qywZ1JuQrmmoToe8mDDYKgCaCWFAmDTVf9VYEhAkP1+igWLB9P/9Voj/RK0gf4JAREXoE5b6fQCC+zXSGmipVHOlbk3/GRqO6d91Y1MxTFN7VQ7+s

