apiVersion: v1
data:
  MONGODB_DB: dXNlcnM=
  MONGODB_HOST: Zmxhc2stYXBwLmNsdXN0ZXItY3lmYzhjcWswYXpxLnVzLWVhc3QtMS5kb2NkYi5hbWF6b25hd3MuY29t
  MONGODB_PASSWORD: eEYwOHNEZzlOMGo1
  MONGODB_USER: cmVzdGFwaQ==
kind: Secret
metadata:
  name: mongodb-credentials
