apiVersion: v1
data:
  MONGODB_DB: dXNlcnM=
  MONGODB_HOST: Zmxhc2stYXBwLmNsdXN0ZXItY290eXE4d2NtaGxsLnVzLWVhc3QtMS5kb2NkYi5hbWF6b25hd3MuY29tCg==
  MONGODB_PASSWORD: eEYwOHNEZzlOMGo1
  MONGODB_USER: cmVzdGFwaQ==
kind: Secret
metadata:
  name: mongodb-credentials
