name: Deploy Kubernetes

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mongomock
        
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::381491904201:role/gh-actions-role
      - name: Docker Build Image
        run: |
          aws sts get-caller-identity
