name: Deploy Kubernetes

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mongomock
        
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::471112901594:role/gh-actions-role
      - name: Build Docker Image
        run: |
          aws sts get-caller-identity

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112901594.dkr.ecr.us-east-1.amazonaws.com
