name: Deploy Kubernetes

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install mongomock
        
  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    env:
      ecr_registry: 797606048546.dkr.ecr.us-east-1.amazonaws.com
      ecr_repository: flask-app-ecr
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - id: build
        name: Build Docker Image
        run: |
          aws sts get-caller-identity

          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${ecr_registry}

          sha=${{ github.sha }}
          short_sha=${sha:0:7}

          docker build -t ${ecr_registry}/${ecr_repository}:dev-${short_sha} .
          docker push ${ecr_registry}/${ecr_repository}:dev-${short_sha}

          echo "image_tag=dev-${short_sha}" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        env:
          TAG: ${{ needs.build.outputs.image_tag }} 
      - name: Deploy to Kubernetes
        run: |
          aws eks update-kubeconfig --name eks-cluster --region us-east-1

          TAG=${{ needs.build.outputs.image_tag }}

          echo "Using Docker image tag: ${TAG}"

          helm upgrade --install restapi kubernetes/charts/restapi-flask --set image.tag=${TAG}